# Generated by Django 3.1.3 on 2020-11-30 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201128_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtema',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=300)),
                ('tema', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, to='accounts.tema')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
            },
        ),
    ]
