# Generated by Django 3.1.3 on 2020-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_asesor_subtetmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='temarioasesor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo/no activo'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='subtetmas',
            field=models.ManyToManyField(through='accounts.TemarioAsesor', to='accounts.Subtema'),
        ),
    ]
