# Generated by Django 3.1.3 on 2020-12-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201207_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='disponible',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Disponible/no disponible'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='subtetmas',
            field=models.ManyToManyField(through='accounts.TemarioAsesor', to='accounts.Subtema'),
        ),
    ]
