# Generated by Django 3.1.3 on 2020-12-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20201212_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.ForeignKey(choices=[('0', 'Lunes'),
                                             ('1', 'Martes'),
                                             ('2', 'Miércoles'),
                                             ('3', 'Jueves'),
                                             ('4', 'Viernes')],
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.catalogodia'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='subtetmas',
            field=models.ManyToManyField(through='accounts.TemarioAsesor', to='accounts.Subtema'),
        ),
        migrations.AlterField(
            model_name='catalogodia',
            name='nombre',
            field=models.CharField(choices=[('0', 'Lunes'),
                                            ('1', 'Martes'),
                                            ('2', 'Miércoles'),
                                            ('3', 'Jueves'),
                                            ('4', 'Viernes')],
                                   max_length=10,
                                   unique=True),
        ),
    ]
