# Generated by Django 3.1.3 on 2020-12-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20201215_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='departamento',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.departamento'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='subtetmas',
            field=models.ManyToManyField(through='accounts.TemarioAsesor', to='accounts.Subtema'),
        ),
    ]
