# Generated by Django 3.1.3 on 2020-11-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201122_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorado',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
