# Generated by Django 3.1.3 on 2020-11-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_asesorado_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorado',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.carrera'),
        ),
    ]
