# Generated by Django 3.1.3 on 2020-11-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201123_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='asesor',
            name='celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='clave_empleado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='accounts.departamento'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asesorado',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='accounts.carrera'),
        ),
        migrations.AlterField(
            model_name='asesorado',
            name='celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asesorado',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='accounts.asesor')),
                ('dia', models.ForeignKey(null=True,
                                          on_delete=django.db.models.deletion.SET_NULL,
                                          to='accounts.diaatencion')),
                ('hora', models.ForeignKey(null=True,
                                           on_delete=django.db.models.deletion.SET_NULL,
                                           to='accounts.horarioatencion')),
            ],
        ),
    ]
