# Generated by Django 3.1.3 on 2020-11-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201124_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='horarios',
            field=models.ManyToManyField(through='accounts.Agenda', to='accounts.DiaAtencion'),
        ),
    ]
