# Generated by Django 3.1.3 on 2020-11-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_temarioasesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='temarioasesor',
            name='asesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.asesor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='temarioasesor',
            unique_together={('materia', 'tema', 'subtema', 'asesor')},
        ),
    ]
