# Generated by Django 3.1.3 on 2020-12-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201129_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterModelOptions(
            name='asesor',
            options={'verbose_name': 'Asesor', 'verbose_name_plural': 'Asesores'},
        ),
        migrations.AlterModelOptions(
            name='asesorado',
            options={'verbose_name': 'Asesorado', 'verbose_name_plural': 'Asesorados'},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='diaatencion',
            options={'verbose_name': 'Día de atención', 'verbose_name_plural': 'Días de atención'},
        ),
        migrations.AlterModelOptions(
            name='horarioatencion',
            options={'verbose_name': 'Horario de atención', 'verbose_name_plural': 'Horarios de atención'},
        ),
        migrations.AlterModelOptions(
            name='jefe',
            options={'verbose_name': 'Jefe', 'verbose_name_plural': 'Jefes'},
        ),
        migrations.AlterField(
            model_name='asesor',
            name='subtetmas',
            field=models.ManyToManyField(through='accounts.TemarioAsesor', to='accounts.Subtema'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='accounts.jefe'),
        ),
        migrations.AlterField(
            model_name='jefe',
            name='celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jefe',
            name='clave_empleado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='clave_materia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
