# Generated by Django 3.1.3 on 2020-12-08 05:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201207_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.ForeignKey(choices=[('lunes', 'Lunes'),
                                             ('martes', 'Martes'), ('miercoles', 'Miércoles'),
                                             ('jueves', 'Jueves'), ('viernes', 'Viernes')],
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.catalogodia'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.ForeignKey(choices=[(datetime.time(7, 0), '07:00'),
                                             (datetime.time(7, 30), '07:30'),
                                             (datetime.time(8, 0), '08:00'),
                                             (datetime.time(8, 30), '08:30'),
                                             (datetime.time(9, 0), '09:00'),
                                             (datetime.time(9, 30), '09:30'),
                                             (datetime.time(10, 0), '10:00'),
                                             (datetime.time(10, 30), '10:30'),
                                             (datetime.time(11, 0), '11:00'),
                                             (datetime.time(11, 30), '11:30'),
                                             (datetime.time(12, 0), '12:00'),
                                             (datetime.time(12, 30), '12:30'),
                                             (datetime.time(13, 0), '13:00'),
                                             (datetime.time(13, 30), '13:30'),
                                             (datetime.time(14, 0), '14:00'),
                                             (datetime.time(14, 30), '14:30'),
                                             (datetime.time(15, 0), '15:00'),
                                             (datetime.time(15, 30), '15:30'),
                                             (datetime.time(16, 0), '16:00'),
                                             (datetime.time(16, 30), '16:30'),
                                             (datetime.time(17, 0), '17:00'),
                                             (datetime.time(17, 30), '17:30'),
                                             (datetime.time(18, 0), '18:00'),
                                             (datetime.time(18, 30), '18:30')],
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.catalogohora'),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='subtetmas',
            field=models.ManyToManyField(through='accounts.TemarioAsesor', to='accounts.Subtema'),
        ),
        migrations.AlterField(
            model_name='catalogodia',
            name='nombre',
            field=models.CharField(choices=[('lunes', 'Lunes'),
                                            ('martes', 'Martes'),
                                            ('miercoles', 'Miércoles'),
                                            ('jueves', 'Jueves'),
                                            ('viernes', 'Viernes')],
                                   max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogohora',
            name='nombre',
            field=models.TimeField(choices=[(datetime.time(7, 0), '07:00'),
                                            (datetime.time(7, 30), '07:30'),
                                            (datetime.time(8, 0), '08:00'),
                                            (datetime.time(8, 30), '08:30'),
                                            (datetime.time(9, 0), '09:00'),
                                            (datetime.time(9, 30), '09:30'),
                                            (datetime.time(10, 0), '10:00'),
                                            (datetime.time(10, 30), '10:30'),
                                            (datetime.time(11, 0), '11:00'),
                                            (datetime.time(11, 30), '11:30'),
                                            (datetime.time(12, 0), '12:00'),
                                            (datetime.time(12, 30), '12:30'),
                                            (datetime.time(13, 0), '13:00'),
                                            (datetime.time(13, 30), '13:30'),
                                            (datetime.time(14, 0), '14:00'),
                                            (datetime.time(14, 30), '14:30'),
                                            (datetime.time(15, 0), '15:00'),
                                            (datetime.time(15, 30), '15:30'),
                                            (datetime.time(16, 0), '16:00'),
                                            (datetime.time(16, 30), '16:30'),
                                            (datetime.time(17, 0), '17:00'),
                                            (datetime.time(17, 30), '17:30'),
                                            (datetime.time(18, 0), '18:00'),
                                            (datetime.time(18, 30), '18:30')],
                                   max_length=10, unique=True),
        ),
    ]
