# Generated by Django 3.1.3 on 2020-12-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0025_auto_20201212_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_asesoria', models.DateTimeField()),
                ('estado', models.CharField(choices=[
                    ('aceptada', 'Aceptada'),
                    ('rechazada', 'Rechazada'),
                    ('cancelada', 'Cancelada'),
                    ('finalizada', 'Finalizada')],
                    max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('comentario_finalizada', models.TextField(blank=True, null=True)),
                ('razon_cancelada', models.TextField(blank=True, null=True)),
                ('razon_rechazada', models.TextField(blank=True, null=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asesor')),
                ('asesorado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asesorado')),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subtema')),
            ],
        ),
    ]
