# Generated by Django 3.1.3 on 2020-12-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesoria',
            options={'verbose_name': 'Asesoria', 'verbose_name_plural': 'Asesorias'},
        ),
    ]
