# Generated by Django 3.1.3 on 2020-12-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0002_auto_20201212_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='comentario_finalizada',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios: asesoría finalizada'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='estado',
            field=models.CharField(choices=[
                ('aceptada', 'Aceptada'),
                ('rechazada', 'Rechazada'),
                ('cancelada', 'Cancelada'),
                ('finalizada', 'Finalizada')],
                max_length=45,
                verbose_name='Estado actual'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='fecha_asesoria',
            field=models.DateTimeField(verbose_name='Fecha asesoría'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='razon_cancelada',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de cancelación'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='razon_rechazada',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de rechazo'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='requisitos',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos previos a la asesoría'),
        ),
    ]
