# Generated by Django 3.1.3 on 2020-12-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0003_auto_20201212_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='estado',
            field=models.CharField(choices=[
                ('pendiente', 'Pendiente'),
                ('aceptada', 'Aceptada'),
                ('rechazada', 'Rechazada'),
                ('cancelada', 'Cancelada'),
                ('finalizada', 'Finalizada')
            ],
                default='pendiente',
                max_length=45,
                verbose_name='Estado actual'),
        ),
    ]
