# Generated by Django 3.1.3 on 2020-12-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0004_auto_20201215_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='agenda',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
